export const DEFAULT_SKIN_ID = "classic";

const REQUIRED_UI_TOKENS = [
  "backgroundStart",
  "backgroundMid",
  "backgroundEnd",
  "ambient",
  "heroStart",
  "heroMid",
  "heroEnd",
  "surface",
  "surfaceStrong",
  "surfaceMuted",
  "text",
  "textMuted",
  "textOnColor",
  "primaryStart",
  "primaryMid",
  "primaryEnd",
  "primaryText",
  "accent",
  "accentSoft",
  "boardFrame",
  "boardStart",
  "boardEnd",
  "boardCellStart",
  "boardCellEnd",
  "shadow",
];

const DEFAULT_VISUAL_PACK = Object.freeze({
  benchmark: false,
  blockMotif: "gloss",
  boardMotif: "clean",
  previewPattern: [0, 1, 5, 8, 9, 10, 14],
  particle: {
    preset: "spark",
    colors: ["#ffffff", "#8eeaff", "#ffe87a", "#ff8fcf"],
  },
  boardClear: {
    preset: "energy",
    glow: "#72e7ff",
    flash: "#ffffff",
    sweep: "#fff17a",
    accent: "#67dfff",
    particlePreset: "spark",
    fragments: "shard",
  },
  fever: {
    preset: "pulse",
    glow: "#65e6ff",
    accent: "#fff17a",
  },
  praiseAccent: ["#ffffff", "#fff17a", "#ff8a52"],
});

function defineVisualPack(visual = {}) {
  return Object.freeze({
    ...DEFAULT_VISUAL_PACK,
    ...visual,
    previewPattern: Object.freeze([
      ...(visual.previewPattern || DEFAULT_VISUAL_PACK.previewPattern),
    ]),
    particle: Object.freeze({
      ...DEFAULT_VISUAL_PACK.particle,
      ...visual.particle,
      colors: Object.freeze([
        ...(visual.particle?.colors || DEFAULT_VISUAL_PACK.particle.colors),
      ]),
    }),
    boardClear: Object.freeze({
      ...DEFAULT_VISUAL_PACK.boardClear,
      ...visual.boardClear,
    }),
    fever: Object.freeze({
      ...DEFAULT_VISUAL_PACK.fever,
      ...visual.fever,
    }),
    praiseAccent: Object.freeze([
      ...(visual.praiseAccent || DEFAULT_VISUAL_PACK.praiseAccent),
    ]),
  });
}

function defineSkin(skin) {
  if (!skin?.id || !skin?.name || skin.swatches?.length < 4) {
    throw new Error("Every skin needs an id, name, and at least four block swatches.");
  }

  for (const token of REQUIRED_UI_TOKENS) {
    if (!skin.ui?.[token]) {
      throw new Error(`Skin "${skin.id}" is missing UI token "${token}".`);
    }
  }

  return Object.freeze({
    ...skin,
    swatches: Object.freeze([...skin.swatches]),
    ui: Object.freeze({ ...skin.ui }),
    visual: defineVisualPack(skin.visual),
  });
}

export const SKINS = Object.freeze([
  defineSkin({
    id: "classic",
    name: "Classic Blue",
    description: "Bright blue arcade",
    rarity: "Default",
    coinPrice: 0,
    unlockRequirement: { type: "default", target: 0 },
    tone: "light",
    swatches: ["#2dd4bf", "#facc15", "#fb7185", "#60a5fa"],
    board: "#142354",
    visual: {
      benchmark: true,
      blockMotif: "classic-cube",
      boardMotif: "blue-grid",
      particle: {
        preset: "spark",
        colors: ["#ffffff", "#7deaff", "#5da9ff", "#fff38a"],
      },
      boardClear: {
        preset: "energy",
        glow: "#54dcff",
        flash: "#f8ffff",
        sweep: "#8eeeff",
        accent: "#4d91ff",
        particlePreset: "spark",
        fragments: "energy-shard",
      },
      fever: { preset: "cyan-pulse", glow: "#36e4ff", accent: "#7eb6ff" },
      praiseAccent: ["#ffffff", "#8ff3ff", "#5f9cff"],
    },
    ui: {
      backgroundStart: "#4662a3",
      backgroundMid: "#344f8d",
      backgroundEnd: "#263b71",
      ambient: "rgba(109, 156, 230, 0.28)",
      heroStart: "#5b43cf",
      heroMid: "#3175ca",
      heroEnd: "#14aea8",
      surface: "rgba(255, 255, 255, 0.88)",
      surfaceStrong: "#ffffff",
      surfaceMuted: "rgba(232, 241, 255, 0.9)",
      text: "#17202a",
      textMuted: "#60707a",
      textOnColor: "#ffffff",
      primaryStart: "#fff06d",
      primaryMid: "#ffb23f",
      primaryEnd: "#ff6f61",
      primaryText: "#3a210b",
      accent: "#fff172",
      accentSoft: "rgba(255, 241, 114, 0.28)",
      boardFrame: "#20254f",
      boardStart: "#16204e",
      boardEnd: "#0c163a",
      boardCellStart: "rgba(65, 87, 151, 0.32)",
      boardCellEnd: "rgba(19, 31, 74, 0.62)",
      shadow: "rgba(10, 16, 44, 0.4)",
    },
  }),
  defineSkin({
    id: "neon",
    name: "Neon Night",
    description: "Electric night glow",
    rarity: "Rare",
    coinPrice: 3000,
    unlockRequirement: { type: "lifetimeBoardClears", target: 30 },
    tone: "dark",
    swatches: ["#00f5ff", "#fc28a8", "#baff29", "#8b5cf6"],
    board: "#10181f",
    ui: {
      backgroundStart: "#171535",
      backgroundMid: "#10162d",
      backgroundEnd: "#080d1c",
      ambient: "rgba(0, 245, 255, 0.18)",
      heroStart: "#351b72",
      heroMid: "#142b61",
      heroEnd: "#043f4d",
      surface: "rgba(20, 24, 45, 0.9)",
      surfaceStrong: "#202744",
      surfaceMuted: "rgba(31, 38, 66, 0.94)",
      text: "#f5f7ff",
      textMuted: "#aab4d6",
      textOnColor: "#ffffff",
      primaryStart: "#baff29",
      primaryMid: "#00f5ff",
      primaryEnd: "#fc28a8",
      primaryText: "#07131a",
      accent: "#00f5ff",
      accentSoft: "rgba(0, 245, 255, 0.2)",
      boardFrame: "#422d73",
      boardStart: "#13182a",
      boardEnd: "#080c16",
      boardCellStart: "rgba(45, 68, 96, 0.52)",
      boardCellEnd: "rgba(9, 17, 29, 0.88)",
      shadow: "rgba(0, 0, 0, 0.56)",
    },
  }),
  defineSkin({
    id: "candy",
    name: "Candy Pop",
    description: "Soft pastel pop",
    rarity: "Common",
    coinPrice: 500,
    unlockRequirement: { type: "lifetimeBoardClears", target: 5 },
    tone: "light",
    swatches: ["#ff8ab3", "#7dd3fc", "#f9a8d4", "#fde047"],
    board: "#5d3a69",
    ui: {
      backgroundStart: "#d96fa5",
      backgroundMid: "#a667bd",
      backgroundEnd: "#655da7",
      ambient: "rgba(255, 225, 244, 0.34)",
      heroStart: "#df6aa7",
      heroMid: "#a86ec3",
      heroEnd: "#668fd2",
      surface: "rgba(255, 248, 253, 0.92)",
      surfaceStrong: "#fffafd",
      surfaceMuted: "rgba(255, 235, 247, 0.94)",
      text: "#42243e",
      textMuted: "#805b78",
      textOnColor: "#ffffff",
      primaryStart: "#fde047",
      primaryMid: "#ff9ebf",
      primaryEnd: "#ff73a8",
      primaryText: "#4a2138",
      accent: "#fff0a6",
      accentSoft: "rgba(255, 240, 166, 0.3)",
      boardFrame: "#6a3f70",
      boardStart: "#58345f",
      boardEnd: "#392744",
      boardCellStart: "rgba(168, 112, 173, 0.42)",
      boardCellEnd: "rgba(67, 39, 75, 0.72)",
      shadow: "rgba(62, 26, 73, 0.42)",
    },
  }),
  defineSkin({
    id: "galaxy",
    name: "Galaxy Rush",
    description: "Deep cosmic violet",
    rarity: "Legendary",
    coinPrice: 12000,
    unlockRequirement: { type: "bestBoardClearStreak", target: 5 },
    tone: "dark",
    swatches: ["#38bdf8", "#a78bfa", "#f472b6", "#22c55e"],
    board: "#15172b",
    visual: {
      benchmark: true,
      blockMotif: "nebula",
      boardMotif: "starfield",
      previewPattern: [0, 3, 5, 6, 9, 10, 12, 15],
      particle: {
        preset: "stardust",
        colors: ["#ffffff", "#71e9ff", "#b59aff", "#ff7bd5"],
      },
      boardClear: {
        preset: "cosmic",
        glow: "#9c7cff",
        flash: "#eafcff",
        sweep: "#5ee7ff",
        accent: "#f06bdc",
        particlePreset: "stardust",
        fragments: "comet",
      },
      fever: { preset: "hyperspace", glow: "#a36dff", accent: "#55e7ff" },
      praiseAccent: ["#ffffff", "#72e9ff", "#d382ff"],
    },
    ui: {
      backgroundStart: "#27245f",
      backgroundMid: "#171944",
      backgroundEnd: "#0b102a",
      ambient: "rgba(119, 99, 255, 0.26)",
      heroStart: "#4b2f91",
      heroMid: "#263c83",
      heroEnd: "#164e72",
      surface: "rgba(24, 25, 56, 0.9)",
      surfaceStrong: "#282a5a",
      surfaceMuted: "rgba(36, 39, 82, 0.94)",
      text: "#f7f5ff",
      textMuted: "#bbb6dc",
      textOnColor: "#ffffff",
      primaryStart: "#74e8ff",
      primaryMid: "#a78bfa",
      primaryEnd: "#f472b6",
      primaryText: "#17112e",
      accent: "#a78bfa",
      accentSoft: "rgba(167, 139, 250, 0.24)",
      boardFrame: "#423d7c",
      boardStart: "#1b1d3b",
      boardEnd: "#0d1024",
      boardCellStart: "rgba(73, 73, 139, 0.46)",
      boardCellEnd: "rgba(20, 22, 53, 0.86)",
      shadow: "rgba(4, 6, 24, 0.56)",
    },
  }),
  defineSkin({
    id: "gold",
    name: "Gold Rush",
    description: "Warm premium finish",
    rarity: "Rare",
    coinPrice: 1500,
    unlockRequirement: { type: "lifetimeBoardClears", target: 15 },
    tone: "dark",
    swatches: ["#f6c453", "#ff8a3d", "#fff0a3", "#d9a118"],
    board: "#2a2010",
    visual: {
      benchmark: true,
      blockMotif: "gold-bar",
      boardMotif: "treasure",
      previewPattern: [0, 1, 2, 5, 6, 9, 10, 13, 14],
      particle: {
        preset: "coin",
        colors: ["#fff8c7", "#ffd45d", "#f5a623", "#ffffff"],
      },
      boardClear: {
        preset: "treasure",
        glow: "#ffd45d",
        flash: "#fff8d0",
        sweep: "#fff0a0",
        accent: "#f59e0b",
        particlePreset: "coin",
        fragments: "coin",
      },
      fever: { preset: "gold-aura", glow: "#ffd45d", accent: "#fff3a6" },
      praiseAccent: ["#fffdf0", "#ffe57a", "#f59e0b"],
    },
    ui: {
      backgroundStart: "#715022",
      backgroundMid: "#47351c",
      backgroundEnd: "#21190f",
      ambient: "rgba(255, 207, 99, 0.24)",
      heroStart: "#8c5c1d",
      heroMid: "#68421d",
      heroEnd: "#3c2c20",
      surface: "rgba(45, 34, 21, 0.92)",
      surfaceStrong: "#4c3922",
      surfaceMuted: "rgba(60, 44, 25, 0.94)",
      text: "#fff7df",
      textMuted: "#d9c39b",
      textOnColor: "#ffffff",
      primaryStart: "#fff0a3",
      primaryMid: "#f6c453",
      primaryEnd: "#ff8a3d",
      primaryText: "#38220a",
      accent: "#f6c453",
      accentSoft: "rgba(246, 196, 83, 0.24)",
      boardFrame: "#6f5122",
      boardStart: "#332713",
      boardEnd: "#171109",
      boardCellStart: "rgba(118, 86, 35, 0.46)",
      boardCellEnd: "rgba(39, 28, 13, 0.9)",
      shadow: "rgba(13, 9, 4, 0.58)",
    },
  }),
  defineSkin({
    id: "ocean",
    name: "Ocean Ice",
    description: "Crisp cyan currents",
    rarity: "Epic",
    coinPrice: 4500,
    unlockRequirement: { type: "lifetimeBoardClears", target: 50 },
    tone: "dark",
    swatches: ["#67e8f9", "#38bdf8", "#a5f3fc", "#2dd4bf"],
    board: "#102c46",
    ui: {
      backgroundStart: "#1b7091",
      backgroundMid: "#15506f",
      backgroundEnd: "#0a2946",
      ambient: "rgba(103, 232, 249, 0.25)",
      heroStart: "#1681a6",
      heroMid: "#14658e",
      heroEnd: "#0f486b",
      surface: "rgba(225, 249, 255, 0.92)",
      surfaceStrong: "#f3fdff",
      surfaceMuted: "rgba(209, 242, 251, 0.94)",
      text: "#0c2d3d",
      textMuted: "#497384",
      textOnColor: "#ffffff",
      primaryStart: "#cffafe",
      primaryMid: "#67e8f9",
      primaryEnd: "#2dd4bf",
      primaryText: "#083344",
      accent: "#a5f3fc",
      accentSoft: "rgba(165, 243, 252, 0.28)",
      boardFrame: "#1d6684",
      boardStart: "#143e5d",
      boardEnd: "#09243d",
      boardCellStart: "rgba(55, 135, 169, 0.42)",
      boardCellEnd: "rgba(10, 42, 68, 0.82)",
      shadow: "rgba(3, 25, 43, 0.5)",
    },
  }),
  defineSkin({
    id: "sakura",
    name: "Sakura Pink",
    description: "Elegant blossom tones",
    rarity: "Epic",
    coinPrice: 6000,
    unlockRequirement: { type: "lifetimeBoardClears", target: 75 },
    tone: "light",
    swatches: ["#fb7185", "#f9a8d4", "#c4b5fd", "#fda4af"],
    board: "#59364f",
    ui: {
      backgroundStart: "#d884a7",
      backgroundMid: "#a96b9d",
      backgroundEnd: "#665382",
      ambient: "rgba(255, 228, 238, 0.34)",
      heroStart: "#d76792",
      heroMid: "#aa6da5",
      heroEnd: "#7771aa",
      surface: "rgba(255, 247, 251, 0.93)",
      surfaceStrong: "#fffafd",
      surfaceMuted: "rgba(255, 234, 243, 0.94)",
      text: "#49283d",
      textMuted: "#845d76",
      textOnColor: "#ffffff",
      primaryStart: "#ffe4e6",
      primaryMid: "#f9a8d4",
      primaryEnd: "#c4b5fd",
      primaryText: "#4c2441",
      accent: "#fecdd3",
      accentSoft: "rgba(254, 205, 211, 0.3)",
      boardFrame: "#754662",
      boardStart: "#613a57",
      boardEnd: "#3c263c",
      boardCellStart: "rgba(160, 91, 133, 0.4)",
      boardCellEnd: "rgba(66, 38, 62, 0.76)",
      shadow: "rgba(57, 27, 53, 0.42)",
    },
  }),
  defineSkin({
    id: "watermelon",
    name: "Watermelon",
    description: "Juicy summer contrast",
    rarity: "Epic",
    coinPrice: 7500,
    unlockRequirement: { type: "bestBoardClearStreak", target: 3 },
    tone: "dark",
    swatches: ["#ef476f", "#7bd389", "#ff6b6b", "#b7efc5"],
    board: "#173f32",
    visual: {
      benchmark: true,
      blockMotif: "watermelon",
      boardMotif: "rind",
      previewPattern: [0, 1, 4, 5, 6, 9, 10, 11, 15],
      particle: {
        preset: "seed",
        colors: ["#171717", "#ff6b86", "#8ce99a", "#ffd1d9"],
      },
      boardClear: {
        preset: "juice",
        glow: "#ff6685",
        flash: "#fff0f4",
        sweep: "#83e69a",
        accent: "#ff4770",
        particlePreset: "seed",
        fragments: "droplet",
      },
      fever: { preset: "juicy-glow", glow: "#ff6685", accent: "#83e69a" },
      praiseAccent: ["#fff7f8", "#ff7890", "#83e69a"],
    },
    ui: {
      backgroundStart: "#28775e",
      backgroundMid: "#225745",
      backgroundEnd: "#14372f",
      ambient: "rgba(239, 71, 111, 0.22)",
      heroStart: "#287a5b",
      heroMid: "#24654e",
      heroEnd: "#7a3349",
      surface: "rgba(25, 54, 45, 0.92)",
      surfaceStrong: "#244c40",
      surfaceMuted: "rgba(32, 68, 56, 0.94)",
      text: "#f4fff8",
      textMuted: "#b6d8c6",
      textOnColor: "#ffffff",
      primaryStart: "#b7efc5",
      primaryMid: "#7bd389",
      primaryEnd: "#ef476f",
      primaryText: "#17342a",
      accent: "#ff8fa3",
      accentSoft: "rgba(255, 143, 163, 0.24)",
      boardFrame: "#326b56",
      boardStart: "#204d3e",
      boardEnd: "#102c25",
      boardCellStart: "rgba(65, 123, 98, 0.44)",
      boardCellEnd: "rgba(18, 51, 42, 0.86)",
      shadow: "rgba(5, 27, 21, 0.52)",
    },
  }),
  defineSkin({
    id: "marble",
    name: "Marble White",
    description: "Clean stone luxury",
    rarity: "Legendary",
    coinPrice: 9000,
    unlockRequirement: { type: "lifetimeBoardClears", target: 100 },
    tone: "light",
    swatches: ["#f8fafc", "#cbd5e1", "#94a3b8", "#e2e8f0"],
    board: "#475569",
    ui: {
      backgroundStart: "#cbd5e1",
      backgroundMid: "#94a3b8",
      backgroundEnd: "#64748b",
      ambient: "rgba(255, 255, 255, 0.38)",
      heroStart: "#e2e8f0",
      heroMid: "#94a3b8",
      heroEnd: "#64748b",
      surface: "rgba(255, 255, 255, 0.94)",
      surfaceStrong: "#ffffff",
      surfaceMuted: "rgba(241, 245, 249, 0.96)",
      text: "#1e293b",
      textMuted: "#64748b",
      textOnColor: "#ffffff",
      primaryStart: "#ffffff",
      primaryMid: "#e2e8f0",
      primaryEnd: "#94a3b8",
      primaryText: "#1e293b",
      accent: "#f8fafc",
      accentSoft: "rgba(255, 255, 255, 0.32)",
      boardFrame: "#64748b",
      boardStart: "#526173",
      boardEnd: "#334155",
      boardCellStart: "rgba(148, 163, 184, 0.44)",
      boardCellEnd: "rgba(51, 65, 85, 0.78)",
      shadow: "rgba(30, 41, 59, 0.38)",
    },
  }),
  defineSkin({
    id: "rainbow",
    name: "Rainbow Fever",
    description: "Legendary full-spectrum rush",
    rarity: "Legendary",
    coinPrice: 15000,
    unlockRequirement: { type: "lifetimeBoardClears", target: 200 },
    tone: "dark",
    swatches: ["#ff5d8f", "#ffd166", "#4cc9f0", "#80ed99", "#b388ff"],
    board: "#191936",
    ui: {
      backgroundStart: "#4b2d83",
      backgroundMid: "#243f78",
      backgroundEnd: "#15152d",
      ambient: "rgba(76, 201, 240, 0.24)",
      heroStart: "#8f3f8f",
      heroMid: "#3f68aa",
      heroEnd: "#279b8c",
      surface: "rgba(27, 28, 61, 0.92)",
      surfaceStrong: "#34366f",
      surfaceMuted: "rgba(39, 42, 84, 0.95)",
      text: "#ffffff",
      textMuted: "#c6c8ed",
      textOnColor: "#ffffff",
      primaryStart: "#ffd166",
      primaryMid: "#4cc9f0",
      primaryEnd: "#ff5d8f",
      primaryText: "#17152f",
      accent: "#ffd166",
      accentSoft: "rgba(255, 209, 102, 0.25)",
      boardFrame: "#554c96",
      boardStart: "#25264e",
      boardEnd: "#111126",
      boardCellStart: "rgba(78, 82, 151, 0.44)",
      boardCellEnd: "rgba(20, 21, 54, 0.88)",
      shadow: "rgba(5, 5, 25, 0.58)",
    },
  }),
]);

const SKIN_BY_ID = new Map(SKINS.map((skin) => [skin.id, skin]));

export function isSkinId(id) {
  return SKIN_BY_ID.has(id);
}

export function getSkin(id) {
  return SKIN_BY_ID.get(id) || SKIN_BY_ID.get(DEFAULT_SKIN_ID);
}

export function getSkinCssVariables(skinOrId) {
  const skin = typeof skinOrId === "string" ? getSkin(skinOrId) : skinOrId;
  const variables = {
    "--theme-bg-start": skin.ui.backgroundStart,
    "--theme-bg-mid": skin.ui.backgroundMid,
    "--theme-bg-end": skin.ui.backgroundEnd,
    "--theme-ambient": skin.ui.ambient,
    "--theme-hero-start": skin.ui.heroStart,
    "--theme-hero-mid": skin.ui.heroMid,
    "--theme-hero-end": skin.ui.heroEnd,
    "--theme-surface": skin.ui.surface,
    "--theme-surface-strong": skin.ui.surfaceStrong,
    "--theme-surface-muted": skin.ui.surfaceMuted,
    "--theme-text": skin.ui.text,
    "--theme-text-muted": skin.ui.textMuted,
    "--theme-text-on-color": skin.ui.textOnColor,
    "--theme-primary-start": skin.ui.primaryStart,
    "--theme-primary-mid": skin.ui.primaryMid,
    "--theme-primary-end": skin.ui.primaryEnd,
    "--theme-primary-text": skin.ui.primaryText,
    "--theme-accent": skin.ui.accent,
    "--theme-accent-soft": skin.ui.accentSoft,
    "--theme-board-frame": skin.ui.boardFrame,
    "--theme-board-start": skin.ui.boardStart,
    "--theme-board-end": skin.ui.boardEnd,
    "--theme-board-cell-start": skin.ui.boardCellStart,
    "--theme-board-cell-end": skin.ui.boardCellEnd,
    "--theme-shadow": skin.ui.shadow,
    "--theme-board": skin.board,
    "--theme-clear-glow": skin.visual.boardClear.glow,
    "--theme-clear-flash": skin.visual.boardClear.flash,
    "--theme-clear-sweep": skin.visual.boardClear.sweep,
    "--theme-clear-accent": skin.visual.boardClear.accent,
    "--theme-fever-glow": skin.visual.fever.glow,
    "--theme-fever-accent": skin.visual.fever.accent,
    "--theme-praise-0": skin.visual.praiseAccent[0],
    "--theme-praise-1": skin.visual.praiseAccent[1],
    "--theme-praise-2": skin.visual.praiseAccent[2],
  };

  skin.swatches.forEach((color, index) => {
    variables[`--skin-${index}`] = color;
  });

  return variables;
}
